import type { CommunityDiscoveryCatalog } from "../domain/types";
import snapshot from "./dalianskyCatalog.snapshot.json";

/**
 * Generated by scripts/import-daliansky-catalog.mjs from one fixed upstream
 * revision. The snapshot is discovery metadata only; it contains no EFI files.
 */
export const dalianskyCatalog = snapshot as CommunityDiscoveryCatalog;
